apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
spec:
  project: default
  source:
    repoURL: https://github.com/Bukola06/microservice-helm.git
    path: helm-charts/microservice
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
